network:
  population:
    excitatory: 1200
    inhibitory: 300
  clusters:
    count: 6
    jep: 3.2
    jip_ratio: 0.75
    jplus:
      - [NaN, NaN]
      - [NaN, NaN]
  connectivity:
    probabilities:
      - [0.2, 0.5]
      - [0.5, 0.5]
    delay: 0.2
    fixed_indegree: false
  weights:
    matrix:
      - [NaN, NaN]
      - [NaN, NaN]
    scale: 1.0
    modifiers:
      ge: 1.2
      gi: 1.0
      gie: 1.0

neuron:
  model: gif_psc_exp
  E_L: 0.0
  V_reset: 0.0
  C_m: 1.0
  t_ref: 5.0
  tau_m:
    excitatory: 20.0
    inhibitory: 10.0
  tau_syn:
    excitatory: 3.0
    inhibitory: 2.0
  V_th:
    excitatory: 15.0
    inhibitory: 15.0
  I_e:
    excitatory: 1.0
    inhibitory: 2.0
  I_th:
    excitatory: 1.25
    inhibitory: 0.78
  I_e_delta:
    excitatory: 0.0
    inhibitory: 0.0
  V_m: rand
  lambda_0: 1000.0
  Delta_V: 1.0e-41
  q_sfa: 0.0
  tau_sfa: 2.0
  q_stc: 0.12777777777777777
  tau_stc: 180.0
  delta: null
  rho: null

synapse:
  plasticity:
    U: 0.2
    u: 0.0
    tau_rec: 120.0
    tau_fac: 0.0
  distribution:
    distribution: normal
    sigma: 0.0
    fraction: false

simulation:
  dt: 0.1
  duration: 1000.0
  warmup: 0.0
  return_weights: false
  n_jobs: 1
  randseed: null

recording:
  voltage: false
  target: all
  interval: 0.1

stimulation:
  background: DC
  amplitude: 0.0
  clusters: null
  starts: []
  ends: []
  multi:
    clusters: null
    times: null
    amps: null
